name: PR Checks

on:
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install PDM
      run: |
        curl -sSL https://pdm-project.org/install-pdm.py | python3 -

    - name: Install dependencies
      run: |
        pdm install -G dev

    - name: Run linting
      run: |
        pdm run check

    - name: Run tests
      run: |
        pdm run test 